FROM microsoft/nanoserver:sac2016
ADD Redis-x64-3.0.504.zip redis.zip
RUN powershell -Command \
    $ErrorActionPreference = 'Stop'; \
    Expand-Archive -Path redis.zip -DestinationPath c:\redis ; \
    Remove-Item redis.zip -Force
WORKDIR /redis
ENTRYPOINT ["redis-server.exe"]

# vim: ft=dockerfile
