FROM microsoft/nanoserver:sac2016
COPY Redis-x64-3.0.504.zip redis.zip
RUN powershell -Command \
    $ErrorActionPreference = 'Stop'; \
    Expand-Archive -Path redis.zip -DestinationPath C:\Redis ; \
    Remove-Item redis.zip -Force
EXPOSE 6379
ENTRYPOINT ["C:\\Redis\\redis-server.exe"]

# vim: ft=dockerfile
