# -----------------------------------------------------------------------------
# Microsoft SQL Server Linux Image
# -----------------------------------------------------------------------------

FROM mcr.microsoft.com/mssql/server:2017-CU11
ENV IMAGE_VERSION 2017-CU11
EXPOSE 1433
