FROM microsoft/nanoserver:sac2016
ADD mysql-5.7.24-winx64.zip mysql.zip
RUN powershell -Command \
    Expand-Archive -Path mysql.zip -DestinationPath scratch ; \
    Remove-Item mysql.zip -Force ; \
    Move-Item -Path scratch\* -Destination C:\MySQL ; \
    C:\MySQL\bin\mysqld.exe --initialize-insecure --console --explicit_defaults_for_timestamp
EXPOSE 3306
ENTRYPOINT ["C:\\MySQL\\bin\\mysqld.exe", "--console"]

# vim: ft=dockerfile
