# -----------------------------------------------------------------------------
# Microsoft SQL Server Windows Image
# -----------------------------------------------------------------------------

FROM microsoft/mssql-server-windows-developer:2017-CU1
ENV IMAGE_VERSION 2017-CU1
EXPOSE 1433
