= steeltoeoss/configserver
:toc: preamble
:toclevels: 1
:!toc-title:
:linkattrs:

SteeltoeOSS https://cloud.spring.io/spring-cloud-config/[Spring Cloud Config Server"] docker image.

== Running

By default, the server listens on port 8888 and gets it configuration from https://github.com/spring-cloud-samples/config-repo.

[NOTE]
Following examples omit common `docker` options such as `-p8888:8888` for purposes of brevity.

.Default Configuration
----
$ docker run steeltoeoss/configserver
----

.Custom Git Repo Configuration
----
$ docker run steeltoeoss/configserver --spring.cloud.config.server.git.uri=https://github.com/myorg/myrepo
----

.Local FileSystem Configuration (Non-Git)
----
$ docker run -v /path/to/my/config:/config steeltoeoss/configserver --spring.profiles.active=native
----

== Resources

|===
|Path |Description

|/_{app}_/_{profile}_
|Configuration data for app in Spring profile

|/_{app}_/_{profile}_/_{label}_
|Add a git label

|/_{app}_/_{profiles}/{label}_/_{path}_
|Environment-specific plain text config file at _{path}_

|===

////
## Security

The server is not secure by default. You can add HTTP Basic
authentication by including an extra dependency on Spring Security
(e.g. via `spring-boot-starter-security`). The user name is "user" and
the password is printed on the console on startup (standard Spring
Boot approach), e.g.

```
2014-10-23 08:55:01.579  INFO 8185 --- [           main] b.a.s.AuthenticationManagerConfiguration : 

Using default security password: 83805c57-8c76-4940-ae17-299359888177


```

There is also a password stored in a keystore in the jar file if you
want to use that for a more realistic simulation of a real system. To
unlock the password you need the full strength JCE extensions
(download from Oracle and unpack the zip then copy the jar files to
`<JAVA_HOME>/jre/lib/security`), and the keystore password ("foobar"
stored in plain text in this README for the purposes of a demo, but in
a real system you would keep it secret and only expose via environment
variables).  The password is bound to the app from the Spring
environment key `keystore.password` (so an OS environment variable
KEYSTORE_PASSWORD works).  E.g.

```
$ KEYSTORE_PASSWORD=foobar java -jar target/*.jar
```
////
