name: Build UAA Server

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/build_uaa_server.yaml'
    - 'uaa-server/**'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build_uaa_server.yaml'
    - 'uaa-server/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: 'write'

env:
  IMAGE_NAME: uaa-server
  REGISTRY: ${{ vars.DOCKER_REGISTRY }}

jobs:
  build-push:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      run: ./build.ps1 -Name '${{ env.IMAGE_NAME }}' -Registry '${{ env.REGISTRY }}' -Tag '${{ env.TAG }}'
      shell: pwsh
      env:
        TAG: ${{ github.event_name == 'pull_request' && format('-t {0}/{1}:pr-{2}', env.REGISTRY, env.IMAGE_NAME, github.event.number) || '' }}

    - name: Login to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: docker push --all-tags ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - uses: actions/github-script@v7
      if: ${{ github.event_name == 'pull_request' }}
      with:
        script: |
            github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `To run the UAA server image built for this pull request:
            \`\`\`bash
            docker run --rm -d --pull=always -p 8080:8080 --name uaa-pr steeltoe.azurecr.io/uaa-server:pr-${{ github.event.number }}
            \`\`\``
            })
