name: Build Eureka Server

on:
  pull_request:
    paths:
    - '.github/workflows/build_eureka_server.yaml'
    - '.github/workflows/build-image.yaml'
    - 'eureka-server/metadata/*'
    - 'eureka-server/patches/*'
    - 'eureka-server/customizations/**'
    - 'eureka-server/source/**'
    - 'build.ps1'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/build_eureka_server.yaml'
    - '.github/workflows/build-image.yaml'
    - 'eureka-server/metadata/*'
    - 'eureka-server/patches/*'
    - 'eureka-server/customizations/**'
    - 'eureka-server/source/**'
    - 'build.ps1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    uses: ./.github/workflows/build-image.yaml
    with:
      image: eureka-server
      description: Eureka Server
    secrets: inherit
